name: chemistru-elements-macro

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run clippy
        run: cargo clippy -p chemistru-elements-macro --no-deps --all-features --all-targets

  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Formatting
        run: cargo fmt -p chemistru-elements-macro --verbose

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build -p chemistru-elements-macro --verbose
      - name: Run tests
        run: cargo test -p chemistru-elements-macro --verbose
