name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Formatting
        run: cargo fmt --verbose

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
